name: memory
description: "A game of memory"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  csv: ^6.0.0
  flutter_gen: ^5.8.0
  syncfusion_flutter_charts: ^27.1.56
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
