name: memory
description: "A game of memory"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  collection: ^1.18.0
  csv: ^6.0.0
  syncfusion_flutter_charts: ^27.1.56

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
